package com.code.monkey.naupark;

public enum ParkingPassCode
{
    EMPLOYEE_PARKING_CODE,
    NORTH_COMMUTER_PARKING_CODE,
    KNOLES_GARAGE_PARKING_CODE,
    SAN_FRANCISCO_PARKING_CODE,
    MOUNTAIN_VIEW_PARKING_CODE,
    SKYVIEW_GARAGE_PARKING_CODE,
    R1_PARKING_CODE,
    R2_PARKING_CODE,
    R3_PARKING_CODE,
    R4_PARKING_CODE,
    R5_PARKING_CODE,
    R6_PARKING_CODE,
    SOUTH_COMMUTER_PARKING_CODE
}
